[package]
name = "duat-treesitter"
version = "0.2.2"
edition = "2024"
authors = ["AhoyISki"]
description = "Plugin for tree-sitter bindings for Duat"
homepage = "https://github.com/AhoyISki/duat-treesitter"
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["tree-sitter", "duat", "plugin"]
categories = ["command-line-utilities", "text-editors", "config"]
include = ["src/*", "queries/*", "build.rs"]

[dependencies]
duat-core = { version = "0.5.3", git = "https://github.com/AhoyISki/duat" }
duat-filetype = { version = "0.2.0", git = "https://github.com/AhoyISki/duat-filetype" }

streaming-iterator = "0.1.9"
tree-sitter = "0.25.6"
tree-sitter-language = "0.1.5"
indoc = "2.0.6"
dlopen-rs = "0.7.3"

[build-dependencies]
dirs-next = "2.0.0"
